#
# Sets some default verbose
#
#/control/verbose 2
#/run/verbose 2
#/tracking/verbose 1
#
# create empty scene
#
/vis/scene/create
#
# Create a scene handler for a specific graphics system
# (Edit the next line(s) to choose another graphic system)
#
/vis/open OGLIX
#
####/vis/open DAWNFILE
#
# draw scene
#
#/vis/scene/add/axes
/vis/viewer/set/viewpointThetaPhi 270 0 deg
/vis/viewer/zoom 0.75
/vis/viewer/flush
#
# for drawing the tracks
# (if too many tracks cause core dump => storeTrajectory 0)
/tracking/storeTrajectory 1
/vis/scene/endOfEventAction accumulate

